### ISSUE TITLE
Syntax error at Client.pm when trying to compile and run the test

### ISSUE THREAD

**Issue by lyhuuloi** [troglodyne/iContact-cPanel-Plugins#11]
Hi,

i installed this plugin successfully, but when i try to run the test, it shows an error. This is the entire log in my test:

```
[root@web scripts]# ./generate_testing_configuration.pl
Please input the provider name you are attempting to test: slack
Please input the 'Slack Incoming Webhook URL(s)' (CONTACTSLACK): https://hooks.slack.com/services/T0C547T5K/BC8PNUHJN/(removed)
Done writing to /root/iContact-cPanel-Plugins/.slacktestrc.
The functional test in t/ should now work when ran like so:
AUTHOR_TESTS=1 prove /root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t
[root@web scripts]# AUTHOR_TESTS=1 prove /root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t
/root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t .. syntax error at /root/iContact-cPanel-Plugins/lib/Cpanel/HTTP/Client.pm line 1, near "package Cpanel::HTTP::Client 0.0"
Compilation failed in require at /root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t line 13.
BEGIN failed--compilation aborted at /root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t line 13.
/root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t .. Dubious, test returned 255 (wstat 65280, 0xff00)
No subtests run

Test Summary Report
-------------------
/root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t (Wstat: 65280 Tests: 0 Failed: 0)
Non-zero exit status: 255
Parse errors: No plan found in TAP output
Files=1, Tests=0, 0 wallclock secs ( 0.03 usr 0.00 sys + 0.06 cusr 0.01 csys = 0.10 CPU)
Result: FAIL
```

My OS is: CentOS 6.10 standard [web] ; cPanel v74.0.6.

Thank for your help.

**Comment by troglodyne** [comment]
Most likely this is due to using the old system perl on cent6? I can certainly replicate this on the platform you've provided. I'm suspecting this is due to the old perl version because it passes when run on the (cPanel provided) perl 5.26 install.

Maybe you'll need to run it with the prove version provided by cPanel instead:
`AUTHOR_TESTS=1 /usr/local/cpanel/3rdparty/perl/526/bin/prove /root/iContact-cPanel-Plugins/t/Cpanel-iContact-Provider-Slack.t`. I'll update the tool for generating the test mapping to check if we're on c6 and give you better suggestions, as there's not much to do about the system perl version being so old it thinks that more modern perlisms are syntax errors :/

**Comment by troglodyne** [comment]
scripts/generate_testing_configuration.pl now will detect whether you are on cPanel and use it's prove version instead when it exists. That should solve this problem.

**Comment by lyhuuloi** [comment]
![image](https://user-images.githubusercontent.com/6936722/45333226-39443900-b59f-11e8-992b-f4102dadb11c.png)
Thank you, it really worked well.
